"""Seed data for Cimbri Wedding Planner.
Values come from Veronica's planning notes and the master vendor document.
This file is the single source of truth for fresh deployments.
"""
import uuid
from datetime import datetime, timezone, timedelta


def _sid():
    return str(uuid.uuid4())


DEFAULT_PROJECT = {
    "id": "singleton",
    "couple_names": "Burak & Veronica",
    "wedding_date": None,
    "location": "Cuneo, Piedmont — Italy",
    "guest_count": 50,
    "target_budget": 15000.0,
    "style_notes": "Soft, elegant, and warm. Sage green, dusty rose, candles, florals, lanterns. An Italian farmhouse celebration with a Turkish corner and a touch of Ireland.",
    "updated_at": datetime.now(timezone.utc).isoformat(),
}


# Dream categories — big buckets the couple organises planning around
DREAM_CATEGORIES = [
    {"id": "venue", "name": "Venue & Catering", "description": "The heart of the day — where you eat, dance, and celebrate.", "color": "sage"},
    {"id": "photography", "name": "Photography", "description": "Still memories from every hour of your day.", "color": "rose"},
    {"id": "video", "name": "Video", "description": "Movement, vows, laughter — saved forever.", "color": "gold"},
    {"id": "florals", "name": "Florals & Decor", "description": "Arches, bouquets, table blooms and ribbons.", "color": "rose"},
    {"id": "music_ceremony", "name": "Ceremony Music", "description": "Live music for the civil rite moment.", "color": "sage"},
    {"id": "music_aperitif", "name": "Aperitif Music", "description": "A warm, acoustic welcome during drinks.", "color": "sage"},
    {"id": "music_dinner", "name": "Dinner Music", "description": "Soft background presence during the meal.", "color": "sage"},
    {"id": "music_dj", "name": "DJ & Dancing", "description": "After cake cutting — lights on the dance floor.", "color": "gold"},
    {"id": "live_art", "name": "Live Art & Sketching", "description": "Watercolor memories made on the spot.", "color": "rose"},
    {"id": "cake", "name": "Cake & Sweets", "description": "The cake table, chocolate fountain and desserts.", "color": "rose"},
    {"id": "guest_corners", "name": "Guest Corners", "description": "Photo corner, guestbook, photobooth, Turkish & Ireland corners.", "color": "gold"},
    {"id": "comfort", "name": "Guest Comfort", "description": "Fans, mosquito spray, sunscreen, water, rice, little kindnesses.", "color": "sage"},
    {"id": "stationery", "name": "Stationery", "description": "Invitations, seating chart, menus, place cards, welcome sign.", "color": "rose"},
    {"id": "accommodation", "name": "Accommodation", "description": "Guest rooms at the venue and nearby stays.", "color": "sage"},
    {"id": "transport", "name": "Transportation", "description": "Getting the couple and guests where they need to be.", "color": "gold"},
    {"id": "other", "name": "Other", "description": "Everything else that makes the day yours.", "color": "gold"},
]


# Dream goals — emotional/visual intentions pulled from Veronica's list
DREAM_GOALS = [
    {"id": "entrance_flowers", "name": "Entrance with flowers & ribbons", "category": "florals", "description": "A beautiful arrival feeling for guests — staircase styled with flowers and colored ribbons."},
    {"id": "civil_arch", "name": "Decorated civil rite arch", "category": "florals", "description": "A floral arch for the ceremony — or styling the venue's existing wooden structure."},
    {"id": "dinner_lighting", "name": "Dinner lighting magic", "category": "florals", "description": "Many lights in the dining area for a romantic, glowing atmosphere."},
    {"id": "table_decor", "name": "Candles, fabrics & florals on tables", "category": "florals", "description": "Layered table compositions — candles, soft fabrics, and small blooms."},
    {"id": "cake_corner", "name": "Cake-cutting table", "category": "cake", "description": "Decorated cake-cutting area with lanterns and star-like light effects."},
    {"id": "chocolate_fountain", "name": "Chocolate fountain", "category": "cake", "description": "A crowd-pleaser sweets moment."},
    {"id": "photo_corner", "name": "Photo corner & guestbook", "category": "guest_corners", "description": "Guests take pictures, paste them in a little album, write dedications."},
    {"id": "photobooth", "name": "Photobooth with props", "category": "guest_corners", "description": "Gadgets, frames, playful props — a fun dedicated photo spot."},
    {"id": "turkish_corner", "name": "Turkish corner", "category": "guest_corners", "description": "A small table/area with Turkish-themed items to honour Veronica's side."},
    {"id": "ireland_corner", "name": "Ireland corner", "category": "guest_corners", "description": "A small Irish-themed nod for the family's Irish side."},
    {"id": "guest_basket", "name": "Guest comfort basket", "category": "comfort", "description": "Mosquito spray, fans, sunscreen, napkins, little kindnesses."},
    {"id": "ceremony_water_rice", "name": "Ceremony water & rice", "category": "comfort", "description": "Bottled water for guests and rice to throw after the civil rite."},
    {"id": "ceremony_live_music", "name": "Live music for the ceremony", "category": "music_ceremony", "description": "A real instrument or voice during the civil rite — subtle, moving."},
    {"id": "aperitif_live_music", "name": "Live music for the aperitif", "category": "music_aperitif", "description": "Acoustic trio or duo while guests arrive and mingle."},
    {"id": "dj_after_cake", "name": "DJ after cake cutting", "category": "music_dj", "description": "Cake first, then the dance floor opens."},
    {"id": "live_sketching", "name": "Live sketching artist", "category": "live_art", "description": "Watercolor portraits of guests — a lovely keepsake."},
    {"id": "photo_main", "name": "Full-day photography", "category": "photography", "description": "Preparations through the final celebration."},
    {"id": "video_main", "name": "Wedding video", "category": "video", "description": "~18 min film with vows, preparations, and party moments."},
    {"id": "wedding_menu", "name": "The wedding meal", "category": "venue", "description": "Aperitif + 3-course menu, local Piedmontese kitchen."},
    {"id": "guest_rooms", "name": "Guest rooms at the venue", "category": "accommodation", "description": "On-site rooms so guests can celebrate freely."},
    {"id": "invitation_suite", "name": "Invitation suite", "category": "stationery", "description": "Invitations, menus, seating chart and welcome sign."},
]


def _s(name, category, price_type, unit_price, deposit=0.0, description="", notes="", dream_goal=None):
    return {
        "id": _sid(),
        "name": name,
        "category": category,
        "dream_goal": dream_goal,
        "description": description,
        "price_type": price_type,
        "unit_price": unit_price,
        "deposit": deposit,
        "notes": notes,
        "active": True,
    }


SEED_VENDORS = [
    # ───────── 1. La Locanda del Nocciolo ─────────
    {
        "id": "vendor-locanda-nocciolo",
        "name": "La Locanda del Nocciolo",
        "categories": ["venue", "accommodation", "cake"],
        "contact_person": "Danila Rossi",
        "phone": "+39 338 894 9541 (Danila) / +39 0173 731323 (venue)",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "Località Chiarene 4, Novello (CN)",
        "notes": "Main contact: Danila Rossi. 9 guest rooms + 10th free for the couple. Gift: 1 overnight stay with breakfast for the couple. Party until 02:00; after midnight €150/hour. Final guest count 2 weeks before. No fireworks; colored fountains/lights possible. Outside wine not allowed.",
        "status": "selected",
        "services": [
            _s("Wedding package — adult", "venue", "per_guest", 80.0, 0.0,
               "Aperitif + lunch/dinner: 3 appetizers, 2 first-course tastings, sorbet, 1 main course, 2 sides. 1 bottle of wine per 4 guests (Arneis/Chardonnay, Dolcetto/Barbera).",
               "Nebbiolo/Barolo/Barbaresco are extra.", dream_goal="wedding_menu"),
            _s("Child menu (5–10 yrs)", "venue", "per_guest", 20.0, 0.0,
               "Prosciutto, penne or ravioli, Milanese with fries or hamburger.", ""),
            _s("Child menu (1–5 yrs) — à la carte", "venue", "custom", 0.0, 0.0,
               "Ordered from the menu on the day.", ""),
            _s("Wedding cake — from venue (per portion)", "venue", "per_guest", 5.0, 0.0,
               "Cake made by the venue.", "", dream_goal="cake_corner"),
            _s("Outside cake — slicing fee (per portion)", "venue", "per_guest", 3.0, 0.0,
               "Certified lab/workshop cake required; invoice/certification needed.", "", dream_goal="cake_corner"),
            _s("Chocolate fountain", "cake", "fixed", 200.0, 0.0,
               "A sweet, memorable station.", "", dream_goal="chocolate_fountain"),
            _s("Bartender", "venue", "fixed", 200.0, 0.0, "On-site bartender for cocktails.", ""),
            _s("Water (per bottle)", "venue", "per_unit", 2.0, 0.0, "", ""),
            _s("Spritz carafe", "venue", "per_unit", 20.0, 0.0, "", ""),
            _s("Late hour after midnight (per hour)", "venue", "per_hour", 150.0, 0.0,
               "Party must finish by 02:00.", ""),
            _s("Guest room (double/triple)", "accommodation", "per_unit", 120.0, 0.0,
               "9 rooms for guests; 10th complimentary for the couple.", "", dream_goal="guest_rooms"),
            _s("Simple table decoration & ribbons", "venue", "per_guest", 0.0, 0.0,
               "Handwritten note: GRATUITO (appears to be offered free).", ""),
        ],
    },
    # ───────── 2. Symon Mattio ─────────
    {
        "id": "vendor-symon-mattio",
        "name": "Symon Mattio — Flower by Sym",
        "categories": ["florals"],
        "contact_person": "Symon Mattio",
        "phone": "+39 392 805 0230",
        "email": "symonmio@gmail.com",
        "website": "",
        "instagram": "flower_by_sym",
        "location": "Cuneo area",
        "notes": "Floral designer — events, weddings, window decoration.",
        "status": "shortlisted",
        "services": [
            _s("Entrance & staircase florals", "florals", "custom", 0.0, 0.0,
               "Entrance styled with flowers and coloured ribbons.", "Price on request.",
               dream_goal="entrance_flowers"),
            _s("Civil rite floral arch", "florals", "custom", 0.0, 0.0,
               "Arch or styling the venue's wooden structure.", "Price on request.",
               dream_goal="civil_arch"),
            _s("Table centerpieces (per table)", "florals", "per_unit", 0.0, 0.0,
               "Candles, fabrics and small blooms per table.", "Price on request.",
               dream_goal="table_decor"),
            _s("Cake-cutting area styling", "florals", "custom", 0.0, 0.0,
               "Lanterns and floral accents for the cake moment.", "", dream_goal="cake_corner"),
        ],
    },
    # ───────── 3. Davide Giuseppe Tolis ─────────
    {
        "id": "vendor-davide-tolis",
        "name": "Davide Giuseppe Tolis — Il fotografo di matrimoni",
        "categories": ["photography"],
        "contact_person": "Davide Giuseppe Tolis",
        "phone": "+39 347 374 4553",
        "email": "info@davidegiuseppetolis.it",
        "website": "davidegiuseppetolis.it",
        "instagram": "",
        "location": "Corso Italia 35/a, 12037 Saluzzo (CN)",
        "notes": "Wedding photographer.",
        "status": "shortlisted",
        "services": [
            _s("Wedding photography — enquiry", "photography", "custom", 0.0, 0.0,
               "Full-day photography — request quote.", "Awaiting quote.",
               dream_goal="photo_main"),
        ],
    },
    # ───────── 4. Max / Maximilliano ─────────
    {
        "id": "vendor-max-maxi",
        "name": "Max / Maximilliano — Photography",
        "categories": ["photography", "video"],
        "contact_person": "Max / Maximilliano",
        "phone": "",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "",
        "notes": "Main package: transport included; 12 hours; 1 photographer; 1-hour prematrimonio; album included. Booking deposit €300 to block the date.",
        "status": "shortlisted",
        "services": [
            _s("Main photo package (12h + album + prematrimonio)", "photography", "fixed", 1300.0, 300.0,
               "Transport, 12 hours, 1 photographer, album, 1h pre-wedding.",
               "€300 deposit blocks the date.", dream_goal="photo_main"),
            _s("Second photographer add-on", "photography", "fixed", 250.0, 0.0,
               "Extra photographer for double coverage.", ""),
            _s("Wedding video (~18 min)", "video", "fixed", 1000.0, 0.0,
               "Audio, vows, preparations and party footage.", "", dream_goal="video_main"),
        ],
    },
    # ───────── 5. Sonia Ricci ─────────
    {
        "id": "vendor-sonia-ricci",
        "name": "Sonia Ricci — Live Sketching",
        "categories": ["live_art", "stationery"],
        "contact_person": "Sonia Ricci",
        "phone": "+39 349 587 9193",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "",
        "notes": "Live sketching can double as entertainment and a keepsake. Styles: contemporary fashion sketch, watercolor, romantic/traditional. 6-10 minutes per couple sketch. Service is manageable for 30-47 guests; typically works from aperitif onward. Sketch cards kept simple and neutral. Can finish portraits later in studio. Also does full stationery suite. Free no-obligation sample sketch on request. ~€300 total with transport.",
        "status": "shortlisted",
        "services": [
            _s("Live sketching — base (2.5h)", "live_art", "fixed", 250.0, 0.0,
               "Minimum live session. Watercolor or fashion sketch style.",
               "From €250; shaped by time/volume.", dream_goal="live_sketching"),
            _s("Live sketching — full afternoon/evening", "live_art", "custom", 0.0, 0.0,
               "Longer on-site presence for bigger parties.", "Price on request.",
               dream_goal="live_sketching"),
            _s("Full stationery suite", "stationery", "custom", 0.0, 0.0,
               "Invitations, seating chart, menus, place cards, welcome sign.", "Discount possible if combined.",
               dream_goal="invitation_suite"),
            _s("Post-event wall portrait of the couple", "live_art", "custom", 0.0, 0.0,
               "Studio-created portrait after the wedding.", ""),
        ],
    },
    # ───────── 6. Heart of Gold ─────────
    {
        "id": "vendor-heart-of-gold",
        "name": "Heart of Gold — Music",
        "categories": ["music_ceremony", "music_aperitif", "music_dinner", "music_dj"],
        "contact_person": "",
        "phone": "",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "",
        "notes": "Folk band with Irish/country/American influences. Trio and duo formats available. Broad repertoire; Spotify-based notes. ~2 hours live repertoire. 3 sound systems. Prices VAT-inclusive. Acoustic setup possible for small groups.",
        "status": "shortlisted",
        "services": [
            _s("Ceremony + DJ", "music_ceremony", "fixed", 1050.0, 0.0,
               "Live ceremony music + DJ for the rest of the evening.",
               "Good value starter package.", dream_goal="ceremony_live_music"),
            _s("Duo + DJ", "music_aperitif", "fixed", 1350.0, 0.0,
               "Duo live + DJ.", "", dream_goal="aperitif_live_music"),
            _s("Trio + DJ", "music_aperitif", "fixed", 1700.0, 0.0,
               "Trio live + DJ.", "", dream_goal="aperitif_live_music"),
            _s("Trio + Violin + DJ", "music_aperitif", "fixed", 2000.0, 0.0,
               "Trio plus violin + DJ.", ""),
            _s("Full band (no DJ)", "music_dinner", "fixed", 1800.0, 0.0,
               "Full band alone.", ""),
            _s("Full band + DJ", "music_dj", "fixed", 2900.0, 0.0,
               "Full band + DJ — the complete package.", "", dream_goal="dj_after_cake"),
        ],
    },
    # ───────── 7. Enzo Granieri / Fotografando ─────────
    {
        "id": "vendor-enzo-fotografando",
        "name": "Enzo Granieri — Fotografando",
        "categories": ["photography", "video"],
        "contact_person": "Enzo Granieri",
        "phone": "+39 011 949 2105 / +39 347 565 3513",
        "email": "fotografando.santena@gmail.com",
        "website": "www.fotografandosantena.it",
        "instagram": "",
        "location": "Via Cavour 48/A, Santena",
        "notes": "Style: spontaneous, natural, largely not posed. Payment can be divided into 3 installments.",
        "status": "shortlisted",
        "services": [
            _s("Photography — files only (high-res)", "photography", "fixed", 650.0, 0.0,
               "All wedding-day photos in high resolution.",
               "Payment in 3 installments possible.", dream_goal="photo_main"),
            _s("Photography + eco-leather album", "photography", "fixed", 1150.0, 0.0,
               "Eco-leather photo book (25x35 or 30x30), 80 post-produced photos with personalized design, 3 selected posters, all wedding-day photos in high resolution.",
               "Payment in 3 installments possible.", dream_goal="photo_main"),
            _s("Wedding video (USB delivery)", "video", "fixed", 550.0, 0.0,
               "Filming from preparation at home, discreet and non-invasive, with edited soundtrack chosen by you, delivered on USB.", "",
               dream_goal="video_main"),
            _s("Drone add-on", "video", "fixed", 150.0, 0.0,
               "Drone photography/videography where permitted.", ""),
        ],
    },
    # ───────── 8. Royal Music / Lorenzo Bongiovanni ─────────
    {
        "id": "vendor-royal-music",
        "name": "Royal Music — Lorenzo Bongiovanni",
        "categories": ["music_ceremony", "music_aperitif", "music_dinner", "music_dj"],
        "contact_person": "Lorenzo Bongiovanni",
        "phone": "+39 393 485 7805",
        "email": "royalmusic.lb@gmail.com",
        "website": "www.royalmusic.it",
        "instagram": "",
        "location": "",
        "notes": "Quote validity: 28/05/2026. 50% or 100% deposit to confirm date and block musicians. Remaining balance due 2 weeks before the wedding. Offers Irish, Turkish, and Italian classics/dance music. Packages cover ceremony, aperitif, dinner, after-dinner DJ with different formations.",
        "status": "shortlisted",
        "services": [
            _s("Base Pack — piano + violin/voice", "music_ceremony", "fixed", 999.0, 500.0,
               "Live ceremony + live aperitif + dinner playlist + after-dinner DJ.",
               "Formation: piano + violin/voice.", dream_goal="ceremony_live_music"),
            _s("Pack — piano + violin + voice", "music_ceremony", "fixed", 1299.0, 650.0,
               "Live ceremony + live aperitif + dinner playlist + after-dinner DJ.",
               "Formation: piano + violin + voice.", dream_goal="ceremony_live_music"),
            _s("Pack Plus — piano + violin + voice + guitar", "music_ceremony", "fixed", 1599.0, 800.0,
               "Full live coverage: ceremony + aperitif + dinner playlist + after-dinner DJ.",
               "Formation: piano + violin + voice + guitar.", dream_goal="ceremony_live_music"),
            _s("DJ Set PRO add-on (after dinner)", "music_dj", "fixed", 399.0, 0.0,
               "Enhanced DJ set.", "", dream_goal="dj_after_cake"),
            _s("Celtic Dances (up to 60 min)", "music_dj", "fixed", 399.0, 0.0,
               "Live performance of Celtic dances — perfect for the Irish side of the celebration.", ""),
            _s("Live interventions between dinner courses", "music_dinner", "fixed", 299.0, 0.0,
               "Live musical moments between courses.",
               "€299 in base packs, €399 in premium pack."),
            _s("Vintage warm lamp (each)", "florals", "per_unit", 49.0, 0.0,
               "Decorative warm vintage lamp.", ""),
            _s("6 Sparkular light fountains", "music_dj", "fixed", 699.0, 0.0,
               "Cold sparkler effect for cake cutting / first dance / grand moments.", "",
               dream_goal="cake_corner"),
            _s("Audio station (1)", "music_aperitif", "fixed", 149.0, 0.0,
               "Sound system rental. 2 stations: €299 · 3 stations: €399 · 4 stations: €449.", ""),
            _s("Wireless microphone (per station)", "music_ceremony", "fixed", 79.0, 0.0,
               "Microphone rental.", ""),
            _s("Vertical piano rental (tuning on site)", "music_ceremony", "fixed", 599.0, 0.0,
               "Piano rental with on-site tuning.", ""),
            _s("4K projector + 84-inch screen", "music_dj", "fixed", 149.0, 0.0,
               "Audio-visual equipment for photo/video slideshow.", ""),
        ],
    },
    # ───────── 9. Music Love Dual Band ─────────
    {
        "id": "vendor-music-love",
        "name": "Music Love Dual Band",
        "categories": ["music_ceremony", "music_aperitif", "music_dinner", "music_dj"],
        "contact_person": "",
        "phone": "",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "",
        "notes": "Looks cheaper up front, but Agibilità, SIAE, Soundreef, VAT are NOT included — real total will be higher. Confirmed by WhatsApp quote.",
        "status": "contacted",
        "services": [
            _s("Pack Duo — Live Music + DJ Set", "music_dj", "fixed", 800.0, 0.0,
               "2 audio stations. Live aperitif with ukulele, male voice, female voice. Playlist during meal. Musical interludes between courses. ~1h30 live music (1970s-disco style). DJ set. Civil rite music included as gift (value ~€250).",
               "Base price. EXCLUDES Agibilità, SIAE, Soundreef, VAT — real total will be higher.",
               dream_goal="aperitif_live_music"),
        ],
    },
    # ───────── 10. Joseph / Josef placeholder ─────────
    {
        "id": "vendor-joseph-tbc",
        "name": "Joseph / Josef (to be confirmed)",
        "categories": ["photography", "video", "music_dj"],
        "contact_person": "Joseph / Josef (introducer)",
        "phone": "",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "",
        "notes": "⚠️ NAME TO BE CONFIRMED — waiting to check with Veronica. Notes mention ~€3000 and ~€2200 all-in price variants, not certain. Full bundle: photo + album + video + drone + potential DJ connections. Transport seems included. Photo/video style customizable. Notes also mention: hidden-battery speakers, no visible wires, ceremony music, fog machine, lights, games, projection — likely overlaps with a music/technical vendor.",
        "status": "new",
        "services": [
            _s("Full photo + video bundle (option A ~€3000)", "photography", "fixed", 3000.0, 0.0,
               "Estimated price from handwritten notes — full bundle: photo + album + video + drone.",
               "⚠️ Price not confirmed — waiting for quote.", dream_goal="photo_main"),
            _s("Full photo + video bundle (option B ~€2200 all-in)", "photography", "fixed", 2200.0, 0.0,
               "Alternative all-in package from notes.",
               "⚠️ Price not confirmed — waiting for quote."),
        ],
    },
    # ───────── 11. Music Vendor A placeholder ─────────
    {
        "id": "vendor-music-a-tbc",
        "name": "Music Vendor A (name to confirm)",
        "categories": ["music_ceremony", "music_aperitif", "music_dinner", "music_dj"],
        "contact_person": "",
        "phone": "",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "",
        "notes": "⚠️ NAME TO BE CONFIRMED. 3-4 person formation (piano + violin + voice for ceremony, guitar for aperitif). 2 DJ sets / moments. Couple can provide own playlist. Live ceremony music, live aperitif, softer dinner music, DJ for ~3 hours. VAT appears included.",
        "status": "new",
        "services": [
            _s("Full day music flow (ceremony → DJ)", "music_ceremony", "custom", 0.0, 0.0,
               "Ceremony + aperitif + dinner + DJ (~3 hours). Formation: 3-4 people (piano + violin + voice + aperitif guitar).",
               "⚠️ Price not confirmed — waiting for quote.", dream_goal="ceremony_live_music"),
        ],
    },
    # ───────── 12. Music Vendor B placeholder ─────────
    {
        "id": "vendor-music-b-tbc",
        "name": "Music Vendor B (name to confirm)",
        "categories": ["music_ceremony", "music_aperitif", "music_dinner", "music_dj"],
        "contact_person": "",
        "phone": "",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "",
        "notes": "⚠️ NAME TO BE CONFIRMED. Pop-style live music package: ceremony + aperitif + dinner + DJ. Duo/trio or full band options. Extra instruments can be added. Travel/transport may be calculated separately. Timing flexibility if they go slightly over.",
        "status": "new",
        "services": [
            _s("Live band — pop genre (customizable)", "music_dj", "custom", 0.0, 0.0,
               "Ceremony + aperitif + dinner + DJ set. Pop-focused. Duo/trio/full band variations.",
               "⚠️ Price and identity to be confirmed."),
        ],
    },
]


def _days(n):
    return (datetime.now(timezone.utc) + timedelta(days=n)).date().isoformat()


SEED_TASKS = [
    {"title": "Finalize venue menu with chef", "category": "venue", "priority": "high", "status": "in_progress",
     "notes": "Ask about Beyti or Lahmacun; mark pork & wine dishes.", "due_date": _days(30)},
    {"title": "Confirm final guest count (2 weeks before)", "category": "venue", "priority": "high", "status": "todo",
     "notes": "Final count no later than 2 weeks before the event.", "due_date": _days(60)},
    {"title": "Book photographer — decide Davide / Max / Enzo", "category": "photography", "priority": "high",
     "status": "todo", "notes": "Compare quotes and portfolios across all 3.", "due_date": _days(20)},
    {"title": "Choose music package — Heart of Gold / Royal Music / Music Love", "category": "music_dj",
     "priority": "high", "status": "todo",
     "notes": "Compare formations and total all-in price (incl. SIAE, VAT).", "due_date": _days(25)},
    {"title": "Confirm florist — Symon Mattio", "category": "florals", "priority": "medium", "status": "todo",
     "notes": "Share palette, venue photos, dream items.", "due_date": _days(35)},
    {"title": "Design Turkish corner", "category": "guest_corners", "priority": "low", "status": "todo",
     "notes": "Collect Turkish items, coordinate with decorator.", "due_date": _days(50)},
    {"title": "Design Ireland corner", "category": "guest_corners", "priority": "low", "status": "todo",
     "notes": "Small, tasteful nod to the Irish side.", "due_date": _days(50)},
    {"title": "Prepare guest comfort baskets", "category": "comfort", "priority": "medium", "status": "todo",
     "notes": "Mosquito spray, fans, sunscreen, napkins.", "due_date": _days(45)},
    {"title": "Check if venue piano is tuned & playable", "category": "music_ceremony", "priority": "low",
     "status": "todo", "notes": "Relevant if we hire a pianist.", "due_date": _days(15)},
    {"title": "Request Sonia Ricci sample sketch", "category": "live_art", "priority": "low", "status": "todo",
     "notes": "Free no-obligation sketch offered.", "due_date": _days(10)},
    {"title": "Clarify Joseph/Josef vendor name & quote", "category": "photography", "priority": "medium",
     "status": "todo", "notes": "Need to confirm exact business name and pricing with Veronica.",
     "due_date": _days(14)},
]
