"""Seed data for Cimbri Wedding Planner — exported from MongoDB.
Single source of truth for fresh deployments.

Update this file by running: python export_db.py
"""
import uuid
from datetime import datetime, timezone, timedelta


def _sid():
    return str(uuid.uuid4())


# ────────────────────────────────────────────
# PROJECT (singleton)
# ────────────────────────────────────────────
DEFAULT_PROJECT = {
    "id": "singleton",
    "couple_names": "Burak & Veronica",
    "wedding_date": None,
    "location": "Cuneo, Piedmont — Italy",
    "guest_count": 50,
    "target_budget": 15000.0,
    "style_notes": "Soft, elegant, and warm. Sage green, dusty rose, candles, florals, lanterns. An Italian farmhouse celebration with a Turkish corner and a touch of Ireland.",
    "updated_at": "2026-05-03T21:22:57.920963+00:00",
}

# ────────────────────────────────────────────
# DREAM CATEGORIES
# ────────────────────────────────────────────
DREAM_CATEGORIES = [
    {
        "id": "venue",
        "name": "Venue & Catering",
        "description": "The heart of the day — where you eat, dance, and celebrate.",
        "color": "sage",
        "custom": False,
    },
    {
        "id": "photography",
        "name": "Photography",
        "description": "Still memories from every hour of your day.",
        "color": "rose",
        "custom": False,
    },
    {
        "id": "video",
        "name": "Video",
        "description": "Movement, vows, laughter — saved forever.",
        "color": "gold",
        "custom": False,
    },
    {
        "id": "florals",
        "name": "Florals & Decor",
        "description": "Arches, bouquets, table blooms and ribbons.",
        "color": "rose",
        "custom": False,
    },
    {
        "id": "music_ceremony",
        "name": "Ceremony Music",
        "description": "Live music for the civil rite moment.",
        "color": "sage",
        "custom": False,
    },
    {
        "id": "music_aperitif",
        "name": "Aperitif Music",
        "description": "A warm, acoustic welcome during drinks.",
        "color": "sage",
        "custom": False,
    },
    {
        "id": "music_dinner",
        "name": "Dinner Music",
        "description": "Soft background presence during the meal.",
        "color": "sage",
        "custom": False,
    },
    {
        "id": "music_dj",
        "name": "DJ & Dancing",
        "description": "After cake cutting — lights on the dance floor.",
        "color": "gold",
        "custom": False,
    },
    {
        "id": "live_art",
        "name": "Live Art & Sketching",
        "description": "Watercolor memories made on the spot.",
        "color": "rose",
        "custom": False,
    },
    {
        "id": "cake",
        "name": "Cake & Sweets",
        "description": "The cake table, chocolate fountain and desserts.",
        "color": "rose",
        "custom": False,
    },
    {
        "id": "guest_corners",
        "name": "Guest Corners",
        "description": "Photo corner, guestbook, photobooth, Turkish & Ireland corners.",
        "color": "gold",
        "custom": False,
    },
    {
        "id": "comfort",
        "name": "Guest Comfort",
        "description": "Fans, mosquito spray, sunscreen, water, rice, little kindnesses.",
        "color": "sage",
        "custom": False,
    },
    {
        "id": "stationery",
        "name": "Stationery",
        "description": "Invitations, seating chart, menus, place cards, welcome sign.",
        "color": "rose",
        "custom": False,
    },
    {
        "id": "accommodation",
        "name": "Accommodation",
        "description": "Guest rooms at the venue and nearby stays.",
        "color": "sage",
        "custom": False,
    },
    {
        "id": "transport",
        "name": "Transportation",
        "description": "Getting the couple and guests where they need to be.",
        "color": "gold",
        "custom": False,
    },
    {
        "id": "other",
        "name": "Other",
        "description": "Everything else that makes the day yours.",
        "color": "gold",
        "custom": False,
    },
]

# ────────────────────────────────────────────
# DREAM GOALS
# ────────────────────────────────────────────
DREAM_GOALS = [
    {
        "id": "entrance_flowers",
        "name": "Entrance with flowers & ribbons",
        "category": "florals",
        "description": "A beautiful arrival feeling for guests — staircase styled with flowers and colored ribbons.",
        "custom": False,
    },
    {
        "id": "civil_arch",
        "name": "Decorated civil rite arch",
        "category": "florals",
        "description": "A floral arch for the ceremony — or styling the venue's existing wooden structure.",
        "custom": False,
    },
    {
        "id": "dinner_lighting",
        "name": "Dinner lighting magic",
        "category": "florals",
        "description": "Many lights in the dining area for a romantic, glowing atmosphere.",
        "custom": False,
    },
    {
        "id": "table_decor",
        "name": "Candles, fabrics & florals on tables",
        "category": "florals",
        "description": "Layered table compositions — candles, soft fabrics, and small blooms.",
        "custom": False,
    },
    {
        "id": "cake_corner",
        "name": "Cake-cutting table",
        "category": "cake",
        "description": "Decorated cake-cutting area with lanterns and star-like light effects.",
        "custom": False,
    },
    {
        "id": "chocolate_fountain",
        "name": "Chocolate fountain",
        "category": "cake",
        "description": "A crowd-pleaser sweets moment.",
        "custom": False,
    },
    {
        "id": "photo_corner",
        "name": "Photo corner & guestbook",
        "category": "guest_corners",
        "description": "Guests take pictures, paste them in a little album, write dedications.",
        "custom": False,
    },
    {
        "id": "photobooth",
        "name": "Photobooth with props",
        "category": "guest_corners",
        "description": "Gadgets, frames, playful props — a fun dedicated photo spot.",
        "custom": False,
    },
    {
        "id": "turkish_corner",
        "name": "Turkish corner",
        "category": "guest_corners",
        "description": "A small table/area with Turkish-themed items to honour Veronica's side.",
        "custom": False,
    },
    {
        "id": "ireland_corner",
        "name": "Ireland corner",
        "category": "guest_corners",
        "description": "A small Irish-themed nod for the family's Irish side.",
        "custom": False,
    },
    {
        "id": "guest_basket",
        "name": "Guest comfort basket",
        "category": "comfort",
        "description": "Mosquito spray, fans, sunscreen, napkins, little kindnesses.",
        "custom": False,
    },
    {
        "id": "ceremony_water_rice",
        "name": "Ceremony water & rice",
        "category": "comfort",
        "description": "Bottled water for guests and rice to throw after the civil rite.",
        "custom": False,
    },
    {
        "id": "ceremony_live_music",
        "name": "Live music for the ceremony",
        "category": "music_ceremony",
        "description": "A real instrument or voice during the civil rite — subtle, moving.",
        "custom": False,
    },
    {
        "id": "aperitif_live_music",
        "name": "Live music for the aperitif",
        "category": "music_aperitif",
        "description": "Acoustic trio or duo while guests arrive and mingle.",
        "custom": False,
    },
    {
        "id": "dj_after_cake",
        "name": "DJ after cake cutting",
        "category": "music_dj",
        "description": "Cake first, then the dance floor opens.",
        "custom": False,
    },
    {
        "id": "live_sketching",
        "name": "Live sketching artist",
        "category": "live_art",
        "description": "Watercolor portraits of guests — a lovely keepsake.",
        "custom": False,
    },
    {
        "id": "photo_main",
        "name": "Full-day photography",
        "category": "photography",
        "description": "Preparations through the final celebration.",
        "custom": False,
    },
    {
        "id": "video_main",
        "name": "Wedding video",
        "category": "video",
        "description": "~18 min film with vows, preparations, and party moments.",
        "custom": False,
    },
    {
        "id": "wedding_menu",
        "name": "The wedding meal",
        "category": "venue",
        "description": "Aperitif + 3-course menu, local Piedmontese kitchen.",
        "custom": False,
    },
    {
        "id": "guest_rooms",
        "name": "Guest rooms at the venue",
        "category": "accommodation",
        "description": "On-site rooms so guests can celebrate freely.",
        "custom": False,
    },
    {
        "id": "invitation_suite",
        "name": "Invitation suite",
        "category": "stationery",
        "description": "Invitations, menus, seating chart and welcome sign.",
        "custom": False,
    },
]

# ────────────────────────────────────────────
# VENDORS (with embedded services)
# ────────────────────────────────────────────
SEED_VENDORS = [
    {
        "id": "vendor-locanda-nocciolo",
        "name": "La Locanda del Nocciolo",
        "categories": [
            "venue",
            "accommodation",
            "cake",
        ],
        "contact_person": "Danila Rossi",
        "phone": "+39 338 894 9541 (Danila) / +39 0173 731323 (venue)",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "Località Chiarene 4, Novello (CN)",
        "notes": "Main contact: Danila Rossi. 9 guest rooms + 10th free for the couple. Gift: 1 overnight stay with breakfast for the couple. Party until 02:00; after midnight €150/hour. Final guest count 2 weeks before. No fireworks; colored fountains/lights possible. Outside wine not allowed.",
        "status": "selected",
        "services": [
            {
                "id": "9e274d14-1f22-4cb7-9ff6-43247abb9e8d",
                "name": "Wedding package — adult",
                "category": "venue",
                "dream_goal": "wedding_menu",
                "description": "Aperitif + lunch/dinner: 3 appetizers, 2 first-course tastings, sorbet, 1 main course, 2 sides. 1 bottle of wine per 4 guests (Arneis/Chardonnay, Dolcetto/Barbera).",
                "price_type": "per_guest",
                "unit_price": 80.0,
                "deposit": 0.0,
                "notes": "Nebbiolo/Barolo/Barbaresco are extra.",
                "active": True,
            },
            {
                "id": "5c29e57e-39aa-4f71-8055-8ba1201989c3",
                "name": "Child menu (5–10 yrs)",
                "category": "venue",
                "dream_goal": None,
                "description": "Prosciutto, penne or ravioli, Milanese with fries or hamburger.",
                "price_type": "per_guest",
                "unit_price": 20.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "ae9f815e-7d52-4318-985b-56b96017212f",
                "name": "Child menu (1–5 yrs) — à la carte",
                "category": "venue",
                "dream_goal": None,
                "description": "Ordered from the menu on the day.",
                "price_type": "custom",
                "unit_price": 0.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "9bbf66e4-f918-4da8-ada0-72a15ae2f83e",
                "name": "Wedding cake — from venue (per portion)",
                "category": "venue",
                "dream_goal": "cake_corner",
                "description": "Cake made by the venue.",
                "price_type": "per_guest",
                "unit_price": 5.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "c0722045-79b9-42a8-a062-9ac3985070ba",
                "name": "Outside cake — slicing fee (per portion)",
                "category": "venue",
                "dream_goal": "cake_corner",
                "description": "Certified lab/workshop cake required; invoice/certification needed.",
                "price_type": "per_guest",
                "unit_price": 3.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "b358b3f6-e99c-417e-a0b5-dfb93c9d8109",
                "name": "Chocolate fountain",
                "category": "cake",
                "dream_goal": "chocolate_fountain",
                "description": "A sweet, memorable station.",
                "price_type": "fixed",
                "unit_price": 200.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "f82d3756-bbb3-4f16-9159-77619aa2b127",
                "name": "Bartender",
                "category": "venue",
                "dream_goal": None,
                "description": "On-site bartender for cocktails.",
                "price_type": "fixed",
                "unit_price": 200.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "18432f2d-7525-408a-bdf6-7c37121d93a6",
                "name": "Water (per bottle)",
                "category": "venue",
                "dream_goal": None,
                "description": "",
                "price_type": "per_unit",
                "unit_price": 2.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "f38b4183-8f9a-41ef-af28-e68aa974b9ab",
                "name": "Spritz carafe",
                "category": "venue",
                "dream_goal": None,
                "description": "",
                "price_type": "per_unit",
                "unit_price": 20.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "d0611409-faee-4e9b-82e9-e0b9a690bdc8",
                "name": "Late hour after midnight (per hour)",
                "category": "venue",
                "dream_goal": None,
                "description": "Party must finish by 02:00.",
                "price_type": "per_hour",
                "unit_price": 150.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "8162fe87-d04e-4f9b-80db-a8f5bc8c2a7a",
                "name": "Guest room (double/triple)",
                "category": "accommodation",
                "dream_goal": "guest_rooms",
                "description": "9 rooms for guests; 10th complimentary for the couple.",
                "price_type": "per_unit",
                "unit_price": 120.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "167d95e5-f71e-40ca-b9df-cf71a38b9876",
                "name": "Simple table decoration & ribbons",
                "category": "venue",
                "dream_goal": None,
                "description": "Handwritten note: GRATUITO (appears to be offered free).",
                "price_type": "per_guest",
                "unit_price": 0.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
        ],
        "created_at": "2026-05-03T21:23:02.024831+00:00",
    },
    {
        "id": "vendor-symon-mattio",
        "name": "Symon Mattio — Flower by Sym",
        "categories": [
            "florals",
        ],
        "contact_person": "Symon Mattio",
        "phone": "+39 392 805 0230",
        "email": "symonmio@gmail.com",
        "website": "",
        "instagram": "flower_by_sym",
        "location": "Cuneo area",
        "notes": "Floral designer — events, weddings, window decoration.",
        "status": "shortlisted",
        "services": [
            {
                "id": "130eb3f9-8c16-43d6-844a-5b9f3e885498",
                "name": "Entrance & staircase florals",
                "category": "florals",
                "dream_goal": "entrance_flowers",
                "description": "Entrance styled with flowers and coloured ribbons.",
                "price_type": "custom",
                "unit_price": 0.0,
                "deposit": 0.0,
                "notes": "Price on request.",
                "active": True,
            },
            {
                "id": "4831cec5-9ea5-4b0a-b14e-74a33a0d193a",
                "name": "Civil rite floral arch",
                "category": "florals",
                "dream_goal": "civil_arch",
                "description": "Arch or styling the venue's wooden structure.",
                "price_type": "custom",
                "unit_price": 0.0,
                "deposit": 0.0,
                "notes": "Price on request.",
                "active": True,
            },
            {
                "id": "a17c5067-efb0-4529-9b8a-3f2e75468540",
                "name": "Table centerpieces (per table)",
                "category": "florals",
                "dream_goal": "table_decor",
                "description": "Candles, fabrics and small blooms per table.",
                "price_type": "per_unit",
                "unit_price": 0.0,
                "deposit": 0.0,
                "notes": "Price on request.",
                "active": True,
            },
            {
                "id": "a5ee7a5c-a9c0-4d6f-a055-792d90ce6c2f",
                "name": "Cake-cutting area styling",
                "category": "florals",
                "dream_goal": "cake_corner",
                "description": "Lanterns and floral accents for the cake moment.",
                "price_type": "custom",
                "unit_price": 0.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
        ],
        "created_at": "2026-05-03T21:23:02.025205+00:00",
    },
    {
        "id": "vendor-davide-tolis",
        "name": "Davide Giuseppe Tolis — Il fotografo di matrimoni",
        "categories": [
            "photography",
        ],
        "contact_person": "Davide Giuseppe Tolis",
        "phone": "+39 347 374 4553",
        "email": "info@davidegiuseppetolis.it",
        "website": "davidegiuseppetolis.it",
        "instagram": "",
        "location": "Corso Italia 35/a, 12037 Saluzzo (CN)",
        "notes": "Wedding photographer.",
        "status": "shortlisted",
        "services": [
            {
                "id": "20065273-fc61-4111-aa21-eefd546f2031",
                "name": "Wedding photography — enquiry",
                "category": "photography",
                "dream_goal": "photo_main",
                "description": "Full-day photography — request quote.",
                "price_type": "custom",
                "unit_price": 0.0,
                "deposit": 0.0,
                "notes": "Awaiting quote.",
                "active": True,
            },
        ],
        "created_at": "2026-05-03T21:23:02.025522+00:00",
    },
    {
        "id": "vendor-max-maxi",
        "name": "Max / Maximilliano — Photography",
        "categories": [
            "photography",
            "video",
        ],
        "contact_person": "Max / Maximilliano",
        "phone": "",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "",
        "notes": "Main package: transport included; 12 hours; 1 photographer; 1-hour prematrimonio; album included. Booking deposit €300 to block the date.",
        "status": "shortlisted",
        "services": [
            {
                "id": "70666f97-4604-4ebd-8d0f-236f9cc33cda",
                "name": "Main photo package (12h + album + prematrimonio)",
                "category": "photography",
                "dream_goal": "photo_main",
                "description": "Transport, 12 hours, 1 photographer, album, 1h pre-wedding.",
                "price_type": "fixed",
                "unit_price": 1300.0,
                "deposit": 300.0,
                "notes": "€300 deposit blocks the date.",
                "active": True,
            },
            {
                "id": "3540cfbc-ce46-4588-b2ad-6f578004fe75",
                "name": "Second photographer add-on",
                "category": "photography",
                "dream_goal": None,
                "description": "Extra photographer for double coverage.",
                "price_type": "fixed",
                "unit_price": 250.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "397db5fd-309e-428c-a780-9ecd3f648487",
                "name": "Wedding video (~18 min)",
                "category": "video",
                "dream_goal": "video_main",
                "description": "Audio, vows, preparations and party footage.",
                "price_type": "fixed",
                "unit_price": 1000.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
        ],
        "created_at": "2026-05-03T21:23:02.025744+00:00",
    },
    {
        "id": "vendor-sonia-ricci",
        "name": "Sonia Ricci — Live Sketching",
        "categories": [
            "live_art",
            "stationery",
        ],
        "contact_person": "Sonia Ricci",
        "phone": "+39 349 587 9193",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "",
        "notes": "Live sketching can double as entertainment and a keepsake. Styles: contemporary fashion sketch, watercolor, romantic/traditional. 6-10 minutes per couple sketch. Service is manageable for 30-47 guests; typically works from aperitif onward. Sketch cards kept simple and neutral. Can finish portraits later in studio. Also does full stationery suite. Free no-obligation sample sketch on request. ~€300 total with transport.",
        "status": "shortlisted",
        "services": [
            {
                "id": "6880bf8a-c5ba-45f2-bec8-447fb4a9240d",
                "name": "Live sketching — base (2.5h)",
                "category": "live_art",
                "dream_goal": "live_sketching",
                "description": "Minimum live session. Watercolor or fashion sketch style.",
                "price_type": "fixed",
                "unit_price": 250.0,
                "deposit": 0.0,
                "notes": "From €250; shaped by time/volume.",
                "active": True,
            },
            {
                "id": "58d42c28-d835-4dcd-b6c7-a2bcab3113ad",
                "name": "Live sketching — full afternoon/evening",
                "category": "live_art",
                "dream_goal": "live_sketching",
                "description": "Longer on-site presence for bigger parties.",
                "price_type": "custom",
                "unit_price": 0.0,
                "deposit": 0.0,
                "notes": "Price on request.",
                "active": True,
            },
            {
                "id": "f343ae50-5f90-453f-8601-9eee19e9b8a0",
                "name": "Full stationery suite",
                "category": "stationery",
                "dream_goal": "invitation_suite",
                "description": "Invitations, seating chart, menus, place cards, welcome sign.",
                "price_type": "custom",
                "unit_price": 0.0,
                "deposit": 0.0,
                "notes": "Discount possible if combined.",
                "active": True,
            },
            {
                "id": "74db1084-973e-434a-8e8f-30634d59029b",
                "name": "Post-event wall portrait of the couple",
                "category": "live_art",
                "dream_goal": None,
                "description": "Studio-created portrait after the wedding.",
                "price_type": "custom",
                "unit_price": 0.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
        ],
        "created_at": "2026-05-03T21:23:02.025976+00:00",
    },
    {
        "id": "vendor-heart-of-gold",
        "name": "Heart of Gold — Music",
        "categories": [
            "music_ceremony",
            "music_aperitif",
            "music_dinner",
            "music_dj",
        ],
        "contact_person": "",
        "phone": "",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "",
        "notes": "Folk band with Irish/country/American influences. Trio and duo formats available. Broad repertoire; Spotify-based notes. ~2 hours live repertoire. 3 sound systems. Prices VAT-inclusive. Acoustic setup possible for small groups.",
        "status": "shortlisted",
        "services": [
            {
                "id": "be6994b9-1231-42f3-b2ea-d7fca9e51dc8",
                "name": "Ceremony + DJ",
                "category": "music_ceremony",
                "dream_goal": "ceremony_live_music",
                "description": "Live ceremony music + DJ for the rest of the evening.",
                "price_type": "fixed",
                "unit_price": 1050.0,
                "deposit": 0.0,
                "notes": "Good value starter package.",
                "active": True,
            },
            {
                "id": "5754a5bd-54ec-4eb3-9ab1-16261befbdc4",
                "name": "Duo + DJ",
                "category": "music_aperitif",
                "dream_goal": "aperitif_live_music",
                "description": "Duo live + DJ.",
                "price_type": "fixed",
                "unit_price": 1350.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "180ad2d8-fa39-4f0f-bbc9-e2cf4540f157",
                "name": "Trio + DJ",
                "category": "music_aperitif",
                "dream_goal": "aperitif_live_music",
                "description": "Trio live + DJ.",
                "price_type": "fixed",
                "unit_price": 1700.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "0e0e376b-b127-4bd8-8c0f-2d212f2d3938",
                "name": "Trio + Violin + DJ",
                "category": "music_aperitif",
                "dream_goal": None,
                "description": "Trio plus violin + DJ.",
                "price_type": "fixed",
                "unit_price": 2000.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "ef0b231d-47c9-45f4-83ac-d1f88ee272e8",
                "name": "Full band (no DJ)",
                "category": "music_dinner",
                "dream_goal": None,
                "description": "Full band alone.",
                "price_type": "fixed",
                "unit_price": 1800.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "11843bcb-909e-43e3-869b-0626fb79a13b",
                "name": "Full band + DJ",
                "category": "music_dj",
                "dream_goal": "dj_after_cake",
                "description": "Full band + DJ — the complete package.",
                "price_type": "fixed",
                "unit_price": 2900.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
        ],
        "created_at": "2026-05-03T21:23:02.026213+00:00",
    },
    {
        "id": "vendor-enzo-fotografando",
        "name": "Enzo Granieri — Fotografando",
        "categories": [
            "photography",
            "video",
        ],
        "contact_person": "Enzo Granieri",
        "phone": "+39 011 949 2105 / +39 347 565 3513",
        "email": "fotografando.santena@gmail.com",
        "website": "www.fotografandosantena.it",
        "instagram": "",
        "location": "Via Cavour 48/A, Santena",
        "notes": "Style: spontaneous, natural, largely not posed. Payment can be divided into 3 installments.",
        "status": "shortlisted",
        "services": [
            {
                "id": "22d66260-81bd-477e-b2c4-5979b6e2dace",
                "name": "Photography — files only (high-res)",
                "category": "photography",
                "dream_goal": "photo_main",
                "description": "All wedding-day photos in high resolution.",
                "price_type": "fixed",
                "unit_price": 650.0,
                "deposit": 0.0,
                "notes": "Payment in 3 installments possible.",
                "active": True,
            },
            {
                "id": "4ac48e6d-7639-4fbc-aa33-a018b3e9d375",
                "name": "Photography + eco-leather album",
                "category": "photography",
                "dream_goal": "photo_main",
                "description": "Eco-leather photo book (25x35 or 30x30), 80 post-produced photos with personalized design, 3 selected posters, all wedding-day photos in high resolution.",
                "price_type": "fixed",
                "unit_price": 1150.0,
                "deposit": 0.0,
                "notes": "Payment in 3 installments possible.",
                "active": True,
            },
            {
                "id": "dcca29e1-51d4-4dd9-8efc-f03cca33d8d7",
                "name": "Wedding video (USB delivery)",
                "category": "video",
                "dream_goal": "video_main",
                "description": "Filming from preparation at home, discreet and non-invasive, with edited soundtrack chosen by you, delivered on USB.",
                "price_type": "fixed",
                "unit_price": 550.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "fb22a738-b8c0-4d9f-81f8-9f0f8cf7996b",
                "name": "Drone add-on",
                "category": "video",
                "dream_goal": None,
                "description": "Drone photography/videography where permitted.",
                "price_type": "fixed",
                "unit_price": 150.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
        ],
        "created_at": "2026-05-03T21:23:02.026457+00:00",
    },
    {
        "id": "vendor-royal-music",
        "name": "Royal Music — Lorenzo Bongiovanni",
        "categories": [
            "music_ceremony",
            "music_aperitif",
            "music_dinner",
            "music_dj",
        ],
        "contact_person": "Lorenzo Bongiovanni",
        "phone": "+39 393 485 7805",
        "email": "royalmusic.lb@gmail.com",
        "website": "www.royalmusic.it",
        "instagram": "",
        "location": "",
        "notes": "Quote validity: 28/05/2026. 50% or 100% deposit to confirm date and block musicians. Remaining balance due 2 weeks before the wedding. Offers Irish, Turkish, and Italian classics/dance music. Packages cover ceremony, aperitif, dinner, after-dinner DJ with different formations.",
        "status": "shortlisted",
        "services": [
            {
                "id": "d7a91fee-98ab-414c-8c05-ed11cc71e682",
                "name": "Base Pack — piano + violin/voice",
                "category": "music_ceremony",
                "dream_goal": "ceremony_live_music",
                "description": "Live ceremony + live aperitif + dinner playlist + after-dinner DJ.",
                "price_type": "fixed",
                "unit_price": 999.0,
                "deposit": 500.0,
                "notes": "Formation: piano + violin/voice.",
                "active": True,
            },
            {
                "id": "5ad9139e-7c0c-46af-9cf6-4c8eec9424f7",
                "name": "Pack — piano + violin + voice",
                "category": "music_ceremony",
                "dream_goal": "ceremony_live_music",
                "description": "Live ceremony + live aperitif + dinner playlist + after-dinner DJ.",
                "price_type": "fixed",
                "unit_price": 1299.0,
                "deposit": 650.0,
                "notes": "Formation: piano + violin + voice.",
                "active": True,
            },
            {
                "id": "4c441909-a8f7-447e-9983-60377983fbda",
                "name": "Pack Plus — piano + violin + voice + guitar",
                "category": "music_ceremony",
                "dream_goal": "ceremony_live_music",
                "description": "Full live coverage: ceremony + aperitif + dinner playlist + after-dinner DJ.",
                "price_type": "fixed",
                "unit_price": 1599.0,
                "deposit": 800.0,
                "notes": "Formation: piano + violin + voice + guitar.",
                "active": True,
            },
            {
                "id": "edff84ce-a070-42a7-ac62-d40c201b8a6b",
                "name": "DJ Set PRO add-on (after dinner)",
                "category": "music_dj",
                "dream_goal": "dj_after_cake",
                "description": "Enhanced DJ set.",
                "price_type": "fixed",
                "unit_price": 399.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "580144e3-6115-43ea-b51c-08d04ebb491b",
                "name": "Celtic Dances (up to 60 min)",
                "category": "music_dj",
                "dream_goal": None,
                "description": "Live performance of Celtic dances — perfect for the Irish side of the celebration.",
                "price_type": "fixed",
                "unit_price": 399.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "abffc3d7-f942-40b4-9474-5f47b118fe1e",
                "name": "Live interventions between dinner courses",
                "category": "music_dinner",
                "dream_goal": None,
                "description": "Live musical moments between courses.",
                "price_type": "fixed",
                "unit_price": 299.0,
                "deposit": 0.0,
                "notes": "€299 in base packs, €399 in premium pack.",
                "active": True,
            },
            {
                "id": "ee1fb5c0-1c2d-43d7-a85c-aee80e2b4131",
                "name": "Vintage warm lamp (each)",
                "category": "florals",
                "dream_goal": None,
                "description": "Decorative warm vintage lamp.",
                "price_type": "per_unit",
                "unit_price": 49.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "f7f82609-6a1d-435a-8dd3-67ef81ef212c",
                "name": "6 Sparkular light fountains",
                "category": "music_dj",
                "dream_goal": "cake_corner",
                "description": "Cold sparkler effect for cake cutting / first dance / grand moments.",
                "price_type": "fixed",
                "unit_price": 699.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "62d33433-4fa6-479a-ad29-d9dd412f2329",
                "name": "Audio station (1)",
                "category": "music_aperitif",
                "dream_goal": None,
                "description": "Sound system rental. 2 stations: €299 · 3 stations: €399 · 4 stations: €449.",
                "price_type": "fixed",
                "unit_price": 149.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "a88f61a5-18bd-4e71-8596-c53a565e2e57",
                "name": "Wireless microphone (per station)",
                "category": "music_ceremony",
                "dream_goal": None,
                "description": "Microphone rental.",
                "price_type": "fixed",
                "unit_price": 79.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "9f6775ef-6185-4d59-b4f7-37cccbc8ff8b",
                "name": "Vertical piano rental (tuning on site)",
                "category": "music_ceremony",
                "dream_goal": None,
                "description": "Piano rental with on-site tuning.",
                "price_type": "fixed",
                "unit_price": 599.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
            {
                "id": "c6a855ff-76c6-4db0-8e79-da14c77affa5",
                "name": "4K projector + 84-inch screen",
                "category": "music_dj",
                "dream_goal": None,
                "description": "Audio-visual equipment for photo/video slideshow.",
                "price_type": "fixed",
                "unit_price": 149.0,
                "deposit": 0.0,
                "notes": "",
                "active": True,
            },
        ],
        "created_at": "2026-05-03T21:23:02.026711+00:00",
    },
    {
        "id": "vendor-music-love",
        "name": "Music Love Dual Band",
        "categories": [
            "music_ceremony",
            "music_aperitif",
            "music_dinner",
            "music_dj",
        ],
        "contact_person": "",
        "phone": "",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "",
        "notes": "Looks cheaper up front, but Agibilità, SIAE, Soundreef, VAT are NOT included — real total will be higher. Confirmed by WhatsApp quote.",
        "status": "contacted",
        "services": [
            {
                "id": "20279d05-4a8d-425e-9dfb-3f58da7d3a52",
                "name": "Pack Duo — Live Music + DJ Set",
                "category": "music_dj",
                "dream_goal": "aperitif_live_music",
                "description": "2 audio stations. Live aperitif with ukulele, male voice, female voice. Playlist during meal. Musical interludes between courses. ~1h30 live music (1970s-disco style). DJ set. Civil rite music included as gift (value ~€250).",
                "price_type": "fixed",
                "unit_price": 800.0,
                "deposit": 0.0,
                "notes": "Base price. EXCLUDES Agibilità, SIAE, Soundreef, VAT — real total will be higher.",
                "active": True,
            },
        ],
        "created_at": "2026-05-03T21:23:02.026966+00:00",
    },
    {
        "id": "vendor-joseph-tbc",
        "name": "Joseph / Josef (to be confirmed)",
        "categories": [
            "photography",
            "video",
            "music_dj",
        ],
        "contact_person": "Joseph / Josef (introducer)",
        "phone": "",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "",
        "notes": "⚠️ NAME TO BE CONFIRMED — waiting to check with Veronica. Notes mention ~€3000 and ~€2200 all-in price variants, not certain. Full bundle: photo + album + video + drone + potential DJ connections. Transport seems included. Photo/video style customizable. Notes also mention: hidden-battery speakers, no visible wires, ceremony music, fog machine, lights, games, projection — likely overlaps with a music/technical vendor.",
        "status": "new",
        "services": [
            {
                "id": "c1e161a3-170c-412d-8e48-e53b39d87545",
                "name": "Full photo + video bundle (option A ~€3000)",
                "category": "photography",
                "dream_goal": "photo_main",
                "description": "Estimated price from handwritten notes — full bundle: photo + album + video + drone.",
                "price_type": "fixed",
                "unit_price": 3000.0,
                "deposit": 0.0,
                "notes": "⚠️ Price not confirmed — waiting for quote.",
                "active": True,
            },
            {
                "id": "22866fbc-c292-43db-a455-409e6f471549",
                "name": "Full photo + video bundle (option B ~€2200 all-in)",
                "category": "photography",
                "dream_goal": None,
                "description": "Alternative all-in package from notes.",
                "price_type": "fixed",
                "unit_price": 2200.0,
                "deposit": 0.0,
                "notes": "⚠️ Price not confirmed — waiting for quote.",
                "active": True,
            },
        ],
        "created_at": "2026-05-03T21:23:02.027182+00:00",
    },
    {
        "id": "vendor-music-a-tbc",
        "name": "Music Vendor A (name to confirm)",
        "categories": [
            "music_ceremony",
            "music_aperitif",
            "music_dinner",
            "music_dj",
        ],
        "contact_person": "",
        "phone": "",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "",
        "notes": "⚠️ NAME TO BE CONFIRMED. 3-4 person formation (piano + violin + voice for ceremony, guitar for aperitif). 2 DJ sets / moments. Couple can provide own playlist. Live ceremony music, live aperitif, softer dinner music, DJ for ~3 hours. VAT appears included.",
        "status": "new",
        "services": [
            {
                "id": "7f3de685-b42a-4479-8a86-0d324cacba7e",
                "name": "Full day music flow (ceremony → DJ)",
                "category": "music_ceremony",
                "dream_goal": "ceremony_live_music",
                "description": "Ceremony + aperitif + dinner + DJ (~3 hours). Formation: 3-4 people (piano + violin + voice + aperitif guitar).",
                "price_type": "custom",
                "unit_price": 0.0,
                "deposit": 0.0,
                "notes": "⚠️ Price not confirmed — waiting for quote.",
                "active": True,
            },
        ],
        "created_at": "2026-05-03T21:23:02.027395+00:00",
    },
    {
        "id": "vendor-music-b-tbc",
        "name": "Music Vendor B (name to confirm)",
        "categories": [
            "music_ceremony",
            "music_aperitif",
            "music_dinner",
            "music_dj",
        ],
        "contact_person": "",
        "phone": "",
        "email": "",
        "website": "",
        "instagram": "",
        "location": "",
        "notes": "⚠️ NAME TO BE CONFIRMED. Pop-style live music package: ceremony + aperitif + dinner + DJ. Duo/trio or full band options. Extra instruments can be added. Travel/transport may be calculated separately. Timing flexibility if they go slightly over.",
        "status": "new",
        "services": [
            {
                "id": "6cf9e1d4-4ec9-43eb-8a3a-4922099825f7",
                "name": "Live band — pop genre (customizable)",
                "category": "music_dj",
                "dream_goal": None,
                "description": "Ceremony + aperitif + dinner + DJ set. Pop-focused. Duo/trio/full band variations.",
                "price_type": "custom",
                "unit_price": 0.0,
                "deposit": 0.0,
                "notes": "⚠️ Price and identity to be confirmed.",
                "active": True,
            },
        ],
        "created_at": "2026-05-03T21:23:02.027593+00:00",
    },
]

# ────────────────────────────────────────────
# SELECTIONS (the actual plan picks)
# ────────────────────────────────────────────
SEED_SELECTIONS = []

# ────────────────────────────────────────────
# TASKS
# ────────────────────────────────────────────
SEED_TASKS = [
    {
        "id": "dc7d7a91-3f70-42f6-935a-3ea21dba1c42",
        "title": "Finalize venue menu with chef",
        "category": "venue",
        "vendor_id": None,
        "due_date": "2026-06-02",
        "priority": "high",
        "status": "in_progress",
        "notes": "Ask about Beyti or Lahmacun; mark pork & wine dishes.",
        "created_at": "2026-05-03T21:23:02.028036+00:00",
    },
    {
        "id": "b4ef815e-e4a6-461c-bee0-11872ffff9d8",
        "title": "Confirm final guest count (2 weeks before)",
        "category": "venue",
        "vendor_id": None,
        "due_date": "2026-07-02",
        "priority": "high",
        "status": "todo",
        "notes": "Final count no later than 2 weeks before the event.",
        "created_at": "2026-05-03T21:23:02.028245+00:00",
    },
    {
        "id": "542c2e95-b35e-4c29-b3c6-8d1200a0a638",
        "title": "Book photographer — decide Davide / Max / Enzo",
        "category": "photography",
        "vendor_id": None,
        "due_date": "2026-05-23",
        "priority": "high",
        "status": "todo",
        "notes": "Compare quotes and portfolios across all 3.",
        "created_at": "2026-05-03T21:23:02.028441+00:00",
    },
    {
        "id": "c74fbd20-8f46-4ef3-ac56-f2ccbaf24373",
        "title": "Choose music package — Heart of Gold / Royal Music / Music Love",
        "category": "music_dj",
        "vendor_id": None,
        "due_date": "2026-05-28",
        "priority": "high",
        "status": "todo",
        "notes": "Compare formations and total all-in price (incl. SIAE, VAT).",
        "created_at": "2026-05-03T21:23:02.028615+00:00",
    },
    {
        "id": "9f5cac7e-3198-41e7-8f91-d5d3507d1605",
        "title": "Confirm florist — Symon Mattio",
        "category": "florals",
        "vendor_id": None,
        "due_date": "2026-06-07",
        "priority": "medium",
        "status": "todo",
        "notes": "Share palette, venue photos, dream items.",
        "created_at": "2026-05-03T21:23:02.028788+00:00",
    },
    {
        "id": "33dde191-2373-46ce-9956-0a5305e50eb7",
        "title": "Design Turkish corner",
        "category": "guest_corners",
        "vendor_id": None,
        "due_date": "2026-06-22",
        "priority": "low",
        "status": "todo",
        "notes": "Collect Turkish items, coordinate with decorator.",
        "created_at": "2026-05-03T21:23:02.028963+00:00",
    },
    {
        "id": "18dd3ffa-73bf-431f-9bde-ada2ee41cffc",
        "title": "Design Ireland corner",
        "category": "guest_corners",
        "vendor_id": None,
        "due_date": "2026-06-22",
        "priority": "low",
        "status": "todo",
        "notes": "Small, tasteful nod to the Irish side.",
        "created_at": "2026-05-03T21:23:02.029133+00:00",
    },
    {
        "id": "441501a3-3ed7-4e4a-8057-31be92aea5e7",
        "title": "Prepare guest comfort baskets",
        "category": "comfort",
        "vendor_id": None,
        "due_date": "2026-06-17",
        "priority": "medium",
        "status": "todo",
        "notes": "Mosquito spray, fans, sunscreen, napkins.",
        "created_at": "2026-05-03T21:23:02.029312+00:00",
    },
    {
        "id": "99951111-19e9-4e8d-8985-9b28df30ec55",
        "title": "Check if venue piano is tuned & playable",
        "category": "music_ceremony",
        "vendor_id": None,
        "due_date": "2026-05-18",
        "priority": "low",
        "status": "todo",
        "notes": "Relevant if we hire a pianist.",
        "created_at": "2026-05-03T21:23:02.029536+00:00",
    },
    {
        "id": "1a0a88f7-0304-4c64-840f-1794da980d44",
        "title": "Request Sonia Ricci sample sketch",
        "category": "live_art",
        "vendor_id": None,
        "due_date": "2026-05-13",
        "priority": "low",
        "status": "todo",
        "notes": "Free no-obligation sketch offered.",
        "created_at": "2026-05-03T21:23:02.029713+00:00",
    },
    {
        "id": "7a9dc5e7-6acc-4a54-a547-c26664c426ee",
        "title": "Clarify Joseph/Josef vendor name & quote",
        "category": "photography",
        "vendor_id": None,
        "due_date": "2026-05-17",
        "priority": "medium",
        "status": "todo",
        "notes": "Need to confirm exact business name and pricing with Veronica.",
        "created_at": "2026-05-03T21:23:02.029880+00:00",
    },
]
